name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install libsox-dev

    - name: Checkout
      uses: actions/checkout@v2-beta

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DESM_PLATFORM=test -DESM_BOARD=native ..

    - name: Build
      run: cmake --build build

    - name: Run
      run: |
        cd build
        set -ex
        wget https://github.com/mryndzionek/trace-decoder/releases/download/v1.0/trace-decoder
        chmod +x trace-decoder
        apps/blink/blink &
        sleep 1
        cat /tmp/esm > blink.data
        ./trace-decoder -i file -m ../apps/blink/include/signals.h blink.data +RTS -N2 > blink.log
        apps/dpp/dpp &
        sleep 1
        cat /tmp/esm > dpp.data
        ./trace-decoder -i file -m ../apps/dpp/include/signals.h dpp.data +RTS -N2 > dpp.log
        apps/smokers/smokers &
        sleep 1
        cat /tmp/esm > smokers.data
        ./trace-decoder -i file -m ../apps/smokers/include/signals.h smokers.data +RTS -N2 > smokers.log
        ls -lh
